### ISSUE TITLE
Graph mode

### ISSUE THREAD

**Issue by ahenkes1** [pedro-r-marques/keras-opt#11]
It seems, the current version does only work in eager mode. Are there plans to get it running in graph mode? I think, all .numpy() calls are then "illegal".

**Comment by pedro-r-marques** [comment]
@ahenkes1 The model is executed in graph mode (i.e. all the cost / gradient computation).

This is achieved by calling tf.function in order to build a graph for the model:
https://github.com/pedro-r-marques/keras-opt/blob/master/keras_opt/scipy_optimizer.py#L30

The Scipy optimization executes via standard numpy operations.
